name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      LARAVEL_BYPASS_ENV_CHECK: 1

    services:
      postgres:
        image: postgis/postgis:18-3.6-alpine
        env:
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: '8.5'
          run-install: true
          cache: true

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: '24'
          run-install: true
          cache: true

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Test Backend
        id: backend-test
        run: composer run test
        continue-on-error: true

      - name: Test Frontend
        id: frontend-test
        run: npm run test
        continue-on-error: true

      - name: Check Results
        if: steps.backend-test.outcome == 'failure' || steps.frontend-test.outcome == 'failure'
        run: exit 1
